packages:
  - apps/*
  - libs/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - prisma
  - styled-components
  - unrs-resolver
